### PR TITLE
fixes #506 ipaddr regression affecting iOS/Windows

### LINKED ISSUE #506: interface/address issue prevents bind/connect
confirmed connect and bind failures on iOS platform, also reported tonight on Windows

msgs over TCP/WS have failed silently/inconsistently after updating to beta 7, but we've pinpointed the issue thanks to @jl777 reporting with @gdamore discussion in [nanomsg gitter chatroom](https://gitter.im/nanomsg/nanomsg).

The problem for me on iOS resolves immediately by reverting
```git
commit a896c3051f1b8a0da4fd92819cca9f102dd610e2
Author: Garrett D'Amore garrett@damore.org
Date: Sun May 31 14:17:08 2015 -0700
fixes #371 Assertion failed: !ipv6 (src/transports/utils/iface.c:88)
```

 accordingly here's #507 submitted under the project's MIT license

### PR DESCRIPTION
**Pull request by reqshark**
Signed-off-by: Bent Cardan <bent@nothingsatisfies.com>

### CODE REVIEW

**Comment by reqshark** [comment]
i watched appveyor pass, updated the commit and got a WS timeout. 

unfortunately this doesn't fix #505

**Comment by gdamore** [comment]
Backing out is probably not the right choice here -- it may be something we do, but ultimately we still need to fix the original bug -- #371

**Comment by wirebirdlabs** [comment]
> Backing out is probably not the right choice here -- it may be something we do, but ultimately we still need to fix the original bug

Agree.

It's possible (likely?) a nuanced bug has arisen based on how https://github.com/nanomsg/nanomsg/commit/a896c3051f1b8a0da4fd92819cca9f102dd610e2 sorts unicast vs multicast addresses.

Meaning, even though that step may have introduced what feels like a regression, it's definitely headed in the right direction, and should not be reverted.

**Comment by reqshark** [comment]
So I'll need to take a closer look at what's actually happening here and report back those findings

**Comment by gdamore** [comment]
So the problem here is that you're attempting to bind to an interface name, which is problematic at best.  Better to bind to an explicit IP address than an interface name.

I need more information about the specific code that is timing out or failing; I'd also like to have some samples that illustrate the interfaces that are plumbed on your system. (Such as the output from ifconfig -a)

Again, if you specify a numeric IP address instead of an interface name, you bypass all this code, and probably save all the problems.

In fact, I feel that using interface names so fundamentally flawed (specific to operating systems, cannot ever work on Windows, and just generally fragile both from an *implementation* choice *and* from an application design view) that I'd like to just rip this functionality out altogether.

To be clear: use of named outbound interfaces (e.g. "lo0") in nanomsg URIs is IMO fundamentally broken, and cannot be solved in any portable fashion.  I'm therefore *strongly* in favor of removing it.

**Comment by reqshark** [comment]
well I'm using IP address numbers, not named interfaces, so apprently I'm not bypassing this code.

I'm taking a look at the call stack right now and I'll update with some more information shortly

**Comment by gdamore** [comment]
Please show me an example of the URL you are binding to.

**Comment by gdamore** [comment]
And ideally also, output from ifconfig -a or whatever analog you have.

**Comment by gdamore** [comment]
Reading the code, the only way you get there is if nn_literal_resolve() fails.  That only fails if you give it an IP address string that it can't parse.

It can parse strings of the form "[::1]" and "127.0.0.1".  Using IPv6 addresses without enclosing brackets likely fails however.

**Comment by gdamore** [comment]
Please also move this to #506.  I'm going to actually close this PR, because no matter what other action we may take on this, accepting this PR isn't one of them.

**Pull request closed without merging**
