### PR TITLE
fixes #504, build error in tcpmux.c

### LINKED ISSUE #504: build failure in tcpmux.c: `../utils/err.h` file not found
courtesy of Apple's Xcode:

yelrgm9cdy

### PR DESCRIPTION
**Pull request by reqshark**
@gdamore, review?

### CODE REVIEW

**Comment by gdamore** [comment]
Looks ok to me.

**Comment by gdamore** [comment]
Resend this with a correct bug report and a comment of the form:

fixes #<number> <synopsis>

Where the number and synopsis are taken from the bug report.  Once that's done, I'll go ahead and fast-forward merge it.

**Comment by reqshark** [comment]
I'll update shortly, this morning

**Comment by reqshark** [comment]
ok, @gdamore I rebased the commit with a reference to the bug report and revised the PR subject to match

**Comment by reqshark** [comment]
BTW the first go around i saw appveyor build pass. 

now it seems to be getting caught up on a WS timeout

**Comment by wirebirdlabs** [comment]
> now it seems to be getting caught up on a WS timeout

Yeah, I've noticed this too. I'm seeing a similar failure mode in some code I'm working on, and have casually been checking into it this week.

For clarity, I'm confident that your PR here is not causing the failure, so this AppVeyor failure, @gdamore, should not gate merging this PR.

**Comment by reqshark** [comment]
thanks for the confirmation @wirebirdlabs, indeed downstream we've experienced some of those idiosyncratic WS timeouts, even on travis CI

**Comment by gdamore** [comment]
I think the windows code is particularly fragile... I have some theories here, but it seems like some tests trash the stack.  The tcp_shutdown test was particularly hard here; once it failed it left the stack in a state that even other tests would fail subsequently.

I've not seen WS timeouts on Travis, although there are *other* bugs there.

**Comment by gdamore** [comment]
Your commit comments are still wrong:

    fix xcode error, #include reference :ear_of_rice: :ear_of_rice:
    Fixes #504

I'll go ahead and fix the comments and commit.  You will probably need to merge or rebase after the fact.

**Comment by gdamore** [comment]
Merged here:

commit 72c695ba64b1cd54c2f8693694e97efbfe168083
Author: Bent Cardan <bent@nothingsatisfies.com>
Date:   Wed Nov 4 07:00:09 2015 -0800

    fixes #504 build failure in tcpmux.c: `../utils/err.h` file not found

**Comment by reqshark** [comment]
I don't think we're looking at bugs necessarily. 

I mean our travis timeouts are classic slow-joiner syndrome.

Also just because we call `nn_connect()` over TCP doesn't mean that we've established anything but an `eid` or `how`, *endpoint identiftier*

**Comment by wirebirdlabs** [comment]
Shall we continue the ws.c test hang conversation over here https://github.com/nanomsg/nanomsg/issues/505

**Comment by reqshark** [comment]
thanks @gdamore for merging/fixing my commits! :sunglasses:  

but you know, emojis are cool for commits sometimes, and yea @wirebirdlabs this PR is history

**Comment by gdamore** [comment]
not a big fan of emoji, but more to the point — i’m trying to enforce a
fairly strict conformance where the bug id and synopsis (as in the github
issues) are reported precisely in the first comment line of a commit.

**Comment by reqshark** [comment]
that makes sense, the first line links/ref to the matter, without having to open a dot dot dot

dot dot dot

**Pull request closed without merging**
