### PR TITLE
cmake: Add initial support for linux

### PR DESCRIPTION
**Pull request by xor-gate**
This adds to initial use of cmake build system on Linux systems. 
Tested under debian 8 amd64.

### CODE REVIEW

**Comment by josephsmeng** [comment]
the author of these CMake files seems like adding a space after each commands, so I think maybe it would be better for as to do the same for the consistency. some lines does not obey this rule, like the `install` command from the src/CMakeLists.txt, I think you can fix this in your pulls. thanks for your codes.

**Comment by xor-gate** [comment]
@josephsmeng you are right, i have improved this and also platform checks are now way better. Now we can use `poll2` syscall if it exists.

**Comment by xor-gate** [comment]
I leave this now as-is because it seems some people already tried to integrate cmake for cross-platform. Probably this can be a good base to have full cross-platform support on QNX,OSX,Solaris etc.

**Comment by gdamore** [comment]
I'm gonna close this, and we'll hope for @JackDunaway to submit a PR addressing this shortly.

**Pull request closed without merging**
