### PR TITLE
Fixes crash when trying to close bipc socket that is yet to be accepted

### PR DESCRIPTION
**Pull request by baxtersa**

### CODE REVIEW

**Comment by gdamore** [comment]
Looks pretty good.  Do the other transports have a similar problem?

**Comment by baxtersa** [comment]
TCP does, but @vseryakov has an open pull request #410 that addresses that transport.  I don't know about ws or tcpmux as I'm tracking the most recent beta release with some cherry-picked commits, not master.

**Comment by gdamore** [comment]
Ok, so I'll have a go at merging these pull requests in the next day or so, once I get a few spare cycles.

**Comment by baxtersa** [comment]
Before we merge this in, it looks like this and #410 fail on windows due to some os differences in how they set errno's for named pipes.  I'm not familiar with Windows system calls at all, but I'm starting to look into it myself.  If you're more familiar I'd gladly appreciate the help.  I'll comment on the TCP pull request as well.

**Comment by gdamore** [comment]
So, I was looking at this, and I think the inproc changes you have made are unrelated.  Please separate those out so that I only have the ipc related change and test, and then I'll merge.

**Comment by baxtersa** [comment]
Sorry, looks like those inproc changes are whitespace issues.  I'll make the change when I have time to get around to it, don't know how soon that will be though as I'm getting close to a release at work.

**Comment by gdamore** [comment]
Sure no sweat.  I could probably make the changes myself if you don’t have
time.

**Comment by gdamore** [comment]
This got fixed in

garrett@Triton{4}% git log src/transports/ipc/bipc.c
commit 827d434c3bc4810c626ed5c881e16be3d40ab12f
Author: Garrett D'Amore <garrett@damore.org>
Date:   Thu Oct 22 16:04:07 2015 -0700

    fixes #469 assertion failure in ipc_shutdown

**Pull request closed without merging**
