### PR TITLE
fixes #625 Switch documentation formatting to asciidoctor

### LINKED ISSUE #625: Switch documentation formatting to asciidoctor
After spending a few hours debugging problems with xmlto and asciidoc, I've decided that these tools represent too high a bar for most folks to work with.  I wound up having to set special environment variables ("XMLTO='xmlto --skip-validation'") and use make -e to build documentation.  I also had to install xmlto, which was a pain because it brings in gnu getopts and a bunch of other crap.  This is ridiculous.

I discovered along the way, asciidoctor, which is written in ruby (bleh), but seems to Just Work.  It formats man pages nicely, and *very* quickly, and supports a number of things much more cleanly and simply than asciidoc (such as inter-document links).  Asciidoctor is installable via "gem install asciidoctor" (so easy!), and the format is a strict superset of asciidoc.

I also btw looked into Markdown, but I'm thinking it would be both a lot more effort to convert to it, and the limitations of Markdown seem to be larger.  (I did look at ronn as well, which is useful for man pages, but wasn't very satisfied with the output it generates.)  Asciidoctor is the clear winner here.

### PR DESCRIPTION
**Pull request by gdamore**
Test... formatted pages can be found at 

http://nanomsg.org/asciidoctor/colony/nanomsg.7.html

Other themes for testing:

asciidoctor:  http://nanomsg.org/asciidoctor/default/nanomsg.7.html
github:  http://nanomsg.org/asciidoctor/github/nanomsg.7.html
golo:  http://nanomsg.org/asciidoctor/golo/nanomsg.7.html
maker: http://nanomsg.org/asciidoctor/maker/nanomsg.7.html
readthedocs: http://nanomsg.org/asciidoctor/readthedocs/nanomsg.7.html
riak:  http://nanomsg.org/asciidoctor/riak/nanomsg.7.html
rubygems: http://nanomsg.org/asciidoctor/rubygems/nanomsg.7.html

The theme is super easy to swap out.  This PR uses colony as the default, but happy to change if there is a strong desire for something else (one of the above, or if someone is a CSS expert and wants to put a better one together...)

### CODE REVIEW

**Comment by shiva** [comment]
@gdamore Would you need cmake support for this? eventually?

**Comment by gdamore** [comment]
Yes

**Comment by JackDunaway** [comment]
@shiva, would you be interested to look into this once we get the main CMake work mainlined?

**Comment by shiva** [comment]
@JackDunaway Absolutely!

**Comment by gdamore** [comment]
I integrated this already.

**Pull request closed without merging**
