### PR TITLE
add iOS binding

### PR DESCRIPTION
**Pull request by reqshark**
nanomsg for iOS: https://github.com/reqshark/nanomsg.ios

### CODE REVIEW

**Comment by reqshark** [comment]
ping @gdamore, can we add the link for iOS?

**Comment by gdamore** [comment]
Yeah, I’ll try to get to it tonight..  Sorry not had much time for nanomsg the last couple of weeks.

	- Garrett

**Comment by reqshark** [comment]
thx @gdamore, cheers :cocktail:

also i was planning to ping you and @djc on cutting the beta-6 release soon

**Comment by gdamore** [comment]
Maybe later this week.  I hope to have some time in the next couple of days to hopefully knock out a few more of the worst issues.

**Pull request merged**
