### PR TITLE
fixes #441 Add Travis CI badge for automated builds on linux

### LINKED ISSUE #441: Add status badges for Travis, AppVeyor, etc.

### PR DESCRIPTION
**Pull request by wirebirdlabs**
Feel free to copy/paste just the link to the top of the readme if  "Build Status" feels noisy; also, looked for AppVeyor build, but it looks like it's not public yet. @gdamore, I'll do what I can to help ease your burden on Windows, since that's one important platform for us, and since it's not your favorite :-)

### CODE REVIEW

**Comment by wirebirdlabs** [comment]
> AppVeyor build, but it looks like it's not public yet

Aha, simply submitting PR kicked off the build here: https://ci.appveyor.com/project/gdamore/nanomsg/build/1.0.33

Is the current link a sandbox before moving to a nanomsg domain, or do you prefer to keep that link for now?

**Comment by gdamore** [comment]
No it's the way Appveyor works.  It ties to a personal GitHub account rather than to a repo or to an org. 

That said I intend to create an Appveyor YAML file from my manual config and commit so others can start if they want to.

**Comment by wirebirdlabs** [comment]
> ties to a personal GitHub account rather than to a repo or to an org

Indeed. Looks like one way to workaround this would be to register the name "nanomsg" as a new AppVeyor account (as per their official support: http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations), then add collaborators and/or team access.

> others can start if they want to

Since it's already configured to run on a PR, that's suitable without opening permissions any further. Probably best we not muck up each other's (or the official) build history with sandbox dev; it's easy enough to set up your own if you're serious.

**Comment by gdamore** [comment]
I believe the public AppVeyor build status is available, just using my name.  I was going to go ahead and put that in the badge, along with the Travis badge, at some point in the near future.

	- Garrett

**Pull request merged**
