### PR TITLE
Experimental Windows XP support

### PR DESCRIPTION
**Pull request by TTimo**
This is the changes we have made for Windows XP support.

This code is working for us in production, but our use case doesn't heavily stress the nanomsg API.

To resolve the symbols problems, we look for the Vista+ only functions at runtime and use them if available. Otherwise the code runs in XP mode.

We also provide a test that highlights some of the problems we are aware of with the XP path (ipc_xp_test.c).

This should be of interest to issues #330 and #334

### CODE REVIEW

**Comment by gdamore** [comment]
To be honest, my gut feeling here is that windows XP ought to be delivered as a different platform support.  That said, I don't regularly deliver software for windows, and certainly not for Windows XP.  Microsoft stopped supporting XP a long time ago -- the last service pack was 6 years ago.   Do we really want to expend effort supporting new software developments for an unsupported legacy platform?

**Comment by djc** [comment]
I don't think the answer should necessarily be no, but it should depend on the amount of complexity, and how well it can be squared off in its own little corner without cluttering the modern stuff.

**Comment by gdamore** [comment]
So, I'd like folks working with Windows and with more knowledge of that platform, to contribute/comment here.  Otherwise this is going to sit in a holding pattern -- I'm neither equipped to determine the correctness of the code, nor to test it.  And, to be completely honest, supporting Windows XP feels like asking a lot since I cannot promise that other changes won't break it.  (I'm already unhappy with having to support Windows at all -- I'd really like to have a "port" lead step up ... I'll post about that on the mailing list.)

**Comment by gdamore** [comment]
So this really should be kept off into a corner, or treated as a fork.

Notably I have zero ability to test this for correct function, and I'm not prepared to support Windows XP.

Longer term, the transport and support layers need to be more pluggable, but that's nigh impossible with the current code base; understanding the FSM sufficiently well to make even an attempt is simply far too high a bar for the usual contributors.

Time continues to progress, meanwhile Windows XP becomes less relevant.  I'm closing this PR.  Folks interested in having this function can find it here, and apply the patch themselves manually.  Presumably they are also equipped to test it for proper functionality; something I simply don't have the resources for.

**Pull request closed without merging**
