### PR TITLE
README updates

### LINKED ISSUE #649: Update README to reflect new CMake build process
Related to #648 and #574, the README needs to reflect the current build toolchain process. For a while, autotools will remain available but deprecated in the README, until CMake is sufficiently fleshed-out.

### PR DESCRIPTION
**Pull request by JackDunaway**
Comments prior to merging? To view a rendered version of this PR, visit: https://github.com/JackDunaway/featherweight-nanomsg/tree/pr-readme-cmake-1

### CODE REVIEW

**Comment by JackDunaway** [comment]
This PR is turning out to be a landing pad for testing/previewing a few nits on the README.

**Comment by gdamore** [comment]
So hopefully its clear that I want to bake the cmake tools a little further before we deprecate autocrap.

That said, this is a step in the right direction, but lets hold off until at least a few nits are resolved (packaging nanocat and documentation generation being the biggest)

**Comment by JackDunaway** [comment]
Precisely; this PR is a placeholder/queue/discussion.

**Comment by JackDunaway** [comment]
@gdamore, would you please review these instructions and then consider mainlining? Working toward eventual replacement of autotools with CMake, this step of updating the "official" instructions should come prior to removing autotools, yet after we've reached some level of success with CMake -- and I feel we've reached, or are at least very close to reaching the right level of success across many platforms. Thanks!

**Comment by gdamore** [comment]
I will review in the next day or so; I actually want this pretty badly, I just want it to be correct.  I'm not sure we're there yet -- but we're close.

**Comment by JackDunaway** [comment]
I have rebased this commit just to keep it up to date and ready to merge soon.

**Comment by gdamore** [comment]
Rebased, and merged (squashed the appveyor & shields commit).

**Pull request closed without merging**
