### PR TITLE
support a callback to intercept fprintf(stderr) into custom handlers

### PR DESCRIPTION
**Pull request by Qix-**
closes #347 

Went in and just adjusted the indentation so this can finally get merged. Rebased on top of current master.

### CODE REVIEW

**Comment by gdamore** [comment]
This looks good.  I'll probably rebase.  It would probably be helpful to have a man page documenting this, but that can wait for later.

**Comment by gdamore** [comment]
Well, except that the compiles failed.  So... not ready yet.

**Comment by Qix-** [comment]
Could have sworn this built 🍨 Just a sec.

**Comment by gdamore** [comment]
Well, a few things....

a) It isn't conflict free...

b) The changed messages are for panics... the program is going to call abort() in those circumstances anyway -- and these should not actually occur (if they do then it's a bug!)

So I'm closing this for now -- if you want to resubmit, please do so *very soon*, as I'm winding up for libnanomsg 1.1.

**Pull request closed without merging**
