### PR TITLE
WebSocket mega-squash

### PR DESCRIPTION
**Pull request by wirebirdlabs**
This single PR is a pretty coherent packaging of 82 commits made during the integration of Autobahn TestSuite integration with Travis CI and AppVeyor in order to fully test the WebSocket transport. Each individual commit is designed to be digestible for code review, and building upon each previous commit should apply cleanly against the master.

### CODE REVIEW

**Comment by wirebirdlabs** [comment]
Merge yet?

**Comment by wirebirdlabs** [comment]
By the way, Travis CI has had 6 passes in a row on this branch, and AppVeyor has only failed on `tcp_shutdown` and `device7`.

Those two tests are known to (periodically) fail at this point -- meaning, all other checks are passing, notably the tests created in this PR.

**Comment by gdamore** [comment]
Sorry, running a little behind, as I've had little time to work on nanomsg this week.  Maybe later today, but more realistically sometime this weekend or even early next week before I get to verifying, reviewing code, and merging.

**Comment by gdamore** [comment]
You'll need to resolve the conflicts, and I'll take some effort to review the actual code changes.  Were do we think we are on readiness for this?  Originally we talked about separating the test cases from the new state machine work you did for websocket.

**Comment by wirebirdlabs** [comment]
> resolve the conflicts

working on it; shouldn't take long.

> Originally we talked about separating the test cases from the new state machine work you did for websocket.

The Autobahn TestSuite is a separate commit, not a separate PR. The reason putting them all in one PR is to ensure they could apply cleanly on the other, so you wouldn't have to figure out the order.

> readiness

Ready.

**Pull request closed without merging**
