### PR TITLE
Fixes crash binding an inproc socket after originally bound socket closes.

### PR DESCRIPTION
**Pull request by baxtersa**
Address issue #411 .

### CODE REVIEW

**Comment by gdamore** [comment]
Running behind on analysis of PRs these days.  But I promise to look this week.

**Comment by baxtersa** [comment]
Not a problem.  Even if this doesn't get merged this week, if I could get some feedback that would be great.

**Comment by gdamore** [comment]
At first blush this looks OK.  To be honest, I'm not that familiar, immediately, with Martin's inproc FSM implementation.  I'd feel better if we could get another reviewer here, but as I said, it *looks* ok to me.

**Comment by gdamore** [comment]
Admittedly what would be enormously helpful here, and is missing from all of this code, are state diagrams, showing each of the various states and transitions.  I'll probably have to draw those out to properly support this code base long term.

**Comment by gdamore** [comment]
I've merged this, but I've rebased your code, fixed the commit comments, and addressed some whitespace problems in your code that showed up when I looked at this in the command line.

The tests passed, so its upstream now.  I'm still not 100% comfortable with the inproc code -- it clearly suffers from some race conditions -- in fact much of libnanomsg feels thread-unsafe to me.  But this is clearly an improvement.

**Pull request closed without merging**
