### PR TITLE
Moving 'tests/bug328.c' to 'pair_tcp.c'. Moving 'tests/bug777.c' into 'inproc_noclose.c'.

### PR DESCRIPTION
**Pull request by metadings**

### CODE REVIEW

**Comment by metadings** [comment]
Now if readded 'bug777.c', so I did just move this into 'inproc_noclose.c'...

**Comment by gdamore** [comment]
What purpose does this PR serve?

**Comment by metadings** [comment]
Just to move names `bug777` (to `inproc_close.c`) and `bug328`(to `pair_tcp.c`).

**Comment by gdamore** [comment]
but what was wrong with the old names.  these were tests for specific bugs described in the given bugids.

**Comment by metadings** [comment]
Well, I thought it is bad, if you have a `build` directory with new commands `bug328`, `bug777`.
I don't know about bugids, where are these bugids defined?

**Comment by Snaipe** [comment]
Those are just tests, the binaries are not installed on the target system. The bug IDs refer to past github issues, in this case #328 and #777. If the problem is about polluting the build directory with seemingly unrelated binaries, I'd suggest putting the binaries produced by `add_libnanomsg_test` into a `test` subdirectory.

**Comment by metadings** [comment]
well... Should I name them `issue*.c`?

**Pull request closed without merging**
